__title__ = "assignment-autograder"
__description__ = "Automatic assignment grading for instructor use in programming courses"
__version__ = "2.15.1"
__author__ = "Stanislav Zmiev"
__author_email__ = "szmiev2000@gmail.com"
__license__ = "MIT"
